name: shellspec

on:
  push:
    branches: [main]
  pull_request:
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: seankoji-com/.github/.github/workflows/reusable-shellspec.yml@e909fe7e3ca259b74359e0f6788d3da49d993830
